import isPhoneNum from './regexp/isPhoneNum';
import isSafari from './regexp/isSafari';
import isMobile from './regexp/isMobile';
import isEmail from './regexp/isEmail';
import isIdCard from './regexp/isIdCard';
import isIpv4 from './regexp/isIpv4';
import isIpv6 from './regexp/isIpv6';
import isArrayEqual from './array/isArrayEqual';
import generateUUID from './random/randomUUID';
import capitalsFirstLetter from './string/capitalsFirstLetter';
export { isPhoneNum, isSafari, isMobile, isEmail, isIdCard, isIpv4, isIpv6, isArrayEqual, generateUUID, capitalsFirstLetter, };
